/*
 * generated by Xtext
 */
package org.xtext.example.guidsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GuiDslRuntimeModule extends org.xtext.example.guidsl.AbstractGuiDslRuntimeModule {

}
